name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 'stable'

      - name: osquery
        run: |
         curl -LO https://pkg.osquery.io/deb/osquery_5.7.0-1.linux_amd64.deb
         sudo dpkg -i osquery_5.7.0-1.linux_amd64.deb

      - name: Verify
        run: make verify

